language: node_js
node_js:
  - 'lts/*'
sudo: false
addons:
  firefox: latest
notifications:
  email: false
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh;
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - pip install --pre jupyterlab
install:
  - jlpm install
  - jlpm run build
before_script:
  - jlpm run build:test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - jlpm test
